"""Compatibility facade for residue-level dataset sources and table loaders."""

from .residue_registry import (
    DBPTM_BENCHMARKS,
    DISPROT_CURRENT_JSON_URL,
    DISPROT_CURRENT_TSV_URL,
    RESIDUE_SOURCE_SPECS,
    BioLipLigandClass,
    DbptmBenchmarkSpec,
    PhosphoElmSourceFilter,
    ResidueSourceName,
    ResidueSourceSpec,
    download_dbptm_benchmark,
    download_disprot_current_json,
    download_disprot_current_tsv,
    download_musitedeep_testdata,
    download_residue_source,
    get_dbptm_benchmark,
    get_residue_source,
    list_dbptm_benchmarks,
    list_residue_sources,
    load_biolip_dataset,
    load_dbptm_benchmark_archive,
    load_dbptm_benchmark_dataset,
    load_disprot_json,
    load_disprot_tsv,
    load_interval_residue_tsv,
    load_musitedeep_fasta,
    load_musitedeep_testdata_dataset,
    load_phosphoelm_dataset,
    load_residue_label_table,
    load_residue_source_dataset,
)


__all__ = [
    "DBPTM_BENCHMARKS",
    "BioLipLigandClass",
    "DISPROT_CURRENT_JSON_URL",
    "DISPROT_CURRENT_TSV_URL",
    "DbptmBenchmarkSpec",
    "PhosphoElmSourceFilter",
    "RESIDUE_SOURCE_SPECS",
    "ResidueSourceName",
    "ResidueSourceSpec",
    "download_dbptm_benchmark",
    "download_disprot_current_json",
    "download_disprot_current_tsv",
    "download_musitedeep_testdata",
    "download_residue_source",
    "get_dbptm_benchmark",
    "get_residue_source",
    "list_dbptm_benchmarks",
    "list_residue_sources",
    "load_biolip_dataset",
    "load_dbptm_benchmark_archive",
    "load_dbptm_benchmark_dataset",
    "load_disprot_json",
    "load_disprot_tsv",
    "load_interval_residue_tsv",
    "load_musitedeep_fasta",
    "load_musitedeep_testdata_dataset",
    "load_phosphoelm_dataset",
    "load_residue_label_table",
    "load_residue_source_dataset",
]
